[package]
name = "runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.27.0", features = ["serde", "event-stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.33.0", features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "time",
<<<<<<< HEAD
    "tracing",
] }
console-subscriber = "0.2.0"
=======
] }
>>>>>>> ca159e0622c5550a49851e7f40a21a46406afaaa
tokio-util = "0.7.9"
dashmap = "5.5.3"
anyhow = "1"
clap = { version = "4.4.6", features = ["derive"] }
futures = "0.3.28"
reqwest = "0.11"
